### ISSUE TITLE
as a standalone?

### ISSUE THREAD

**Issue by mimoo** [trailofbits/zkdocs#1]
Hey hey,

This project is amazing! Have you thought about releasing this as something that can be used individually by projects to spec their protocols? I would probably use it in a heartbeat :)

**Comment by fcasal** [comment]
Hi @mimoo, thanks! 
Yes, I have thought about integrating ZKDocs' protocol writing and interactive renaming in a simple note-taking app. My use cases would be quick protocol typesetting (in markdown and latex) and exporting as pdf or image. Did you have anything else in mind?

**Comment by mimoo** [comment]
I think I'd like to use this to specify our protocols over at https://github.com/o1-labs/proof-systems

**Comment by mimoo** [comment]
nevermind it's driven by hugo so using this is actually much simpler than what I thought :) closing this
