### ISSUE TITLE
"Paillier-Blum Modulus" parameter choice reference

### ISSUE THREAD

**Issue by tyurek** [trailofbits/zkdocs#8]
On the Paillier-Blum Modulus page (content/docs/zkdocs/zero-knowledge-protocols/product-primes/paillier_blum_modulus.md), it mentions choosing a modulus size of 2048 to get 80 bits of security. By any chance, could someone include a reference for why this modulus size yields this security and ideally which size is needed to target different security levels?

Thanks

**Comment by fcasal** [comment]
Hi @tyurek, the choice of the modulus size is not exactly what achieves 80 bits of security for the zero knowledge protocol, but setting `m` equal to 80, where `m` is the number of triples (x, a, b) that the prover needs to send. Why this achieves 80 bits of security is described in the referenced paper https://eprint.iacr.org/2021/060.pdf

For the factoring problem, choosing 2048 for the modulus size achieves 112 bits of security and allows a safe margin on these 80 bits of security. The reference here is NIST's document comparing key sizes (https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final table 2 page 54).
